package(default_visibility = ["//visibility:public"])

py_library(
    name = "treeify",
    srcs = ["treeify.py"],
    deps = [
    ],
)

py_test(
    name = "treeify_test",
    srcs = ["treeify_test.py"],
    deps = [
        ":treeify",
    ],
)
