package(default_visibility = ["//visibility:public"])

filegroup(
    name = "example",
    srcs = [
        "example.beancount",
    ],
)

filegroup(
    name = "simple",
    srcs = [
        "simple/basic.beancount",
        "simple/starter.beancount",
    ],
)
