"""
Rules for adding './configure && make' style dependencies.
"""

licenses(["notice"])  # Apache v2.0

package(
    default_visibility = ["//:__subpackages__"],
)

exports_files([
    "bison.bzl",
    "reflex.bzl",
])
