from typing import Any, Dict, List, Tuple

__all__ = ["build_options_map", "load_file", "parse_string", "py_date"]

def load_file(filename: str) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def parse_string(
    content: str, filename: str | None
) -> Tuple[List[Any], List[Any], Dict[str, Any]]: ...
def build_options_map(filename: str) -> Dict[str, Any]: ...
def py_date(date: str) -> Any: ...
